### ISSUE TITLE
Tea spoons

### ISSUE THREAD

**Issue by rayman89** [falk-hueffner/metric-cooking#4]
In this page "2 ts yeast" appears and it's not converted. I read in an other thread that if it's less than 4grams then it's not converted but 2ts is around 10grams so is this a bug or something?

Site: https://www.maangchi.com/recipe/hotteok

**Comment by falk-hueffner** [comment]
I changed it to recognize "ts" as teaspoon, this was an unusual abbreviation so it wasn't so far recognized. The will be in the next update of the add-on.
