### ISSUE TITLE
"1 gallon warm water" is not being converted

### ISSUE THREAD

**Issue by diamondavocado** [falk-hueffner/metric-cooking#9]
"1 gallon warm water" is not being converted, e.g., here:
https://www.allrecipes.com/recipe/170656/simple-chicken-brine/

**Comment by falk-hueffner** [comment]
Heh, I've so far not seen a recipe that needs a whole gallon of something :-) Should be easy to add though...

**Comment by rubdos** [comment]
Quite typical in brewers recipes too, to do gallons, apparently.

This seems to be fixed in 6171466a, but still unreleased on AMO?

**Comment by diamondavocado** [comment]
@falk-hueffner I saw you added gallons in the most recent commit. However despite updating to v1.6, my Firefox extension still isn't converting gallons on the example page I provided.

Is the latest version hosted on Mozilla Addons? If not, can you please kindly update it?

**Comment by falk-hueffner** [comment]
This should be fixed now in 1.7.
